services:
  prometheus:
    image: prom/prometheus:v3.3.0
    ports:
      - 9000:9090
    volumes:
      - ./prometheus:/etc/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana:11.6.1
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - grafana-data:/var/lib/grafana  
  pyroscope:
    image: grafana/pyroscope:latest
    ports:
      - "4040:4040"
    environment:
      - PYROSCOPE_RETENTION=168h  # 7 days
      - PYROSCOPE_LOG_LEVEL=info
  loki:
    image: bitnami/grafana-loki:3.5.0
    ports:
      - "3100:3100"
    volumes:
      - ./loki/config.yaml:/bitnami/grafana-loki/conf/loki.yaml

volumes:
  grafana-data: