services:
  prometheus:
    image: prom/prometheus:v3.3.0
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
    command: --web.enable-lifecycle --web.enable-remote-write-receiver  --config.file=/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana:11.6.1
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - grafana-data:/var/lib/grafana  
  pyroscope:
    image: grafana/pyroscope:latest
    ports:
      - "4040:4040"
    environment:
      - PYROSCOPE_RETENTION=168h  # 7 days
      - PYROSCOPE_LOG_LEVEL=info
  loki:
    image: grafana/loki:3.5.0
    ports:
      - "3100:3100"
    volumes:
      - ./loki/config.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
  statsd:
    image: "prom/statsd-exporter:v0.24.0"
    ports:
      - "9102:9102"
  alloy:
    image: grafana/alloy:v1.8.2
    ports:
      - 12345:12345
      - 4317:4317
      - 4318:4318
    volumes:
      - ./alloy/config.alloy:/etc/alloy/config.alloy
      - /var/run/docker.sock:/var/run/docker.sock
    command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy

volumes:
  grafana-data: