global:
  scrape_interval: 10s
  scrape_timeout: 5s

scrape_configs:
  - job_name: services
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'prometheus:9090'
          - 'statsd:9102'